{
 "title": "Trading Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "account_id",
    "label": "account_id",
    "query": "SELECT DISTINCT(account_id) FROM public.tinvest_operations"
   }
  ]
 },
 "panels": [
  {
   "title": "Текущий баланс портфеля",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time_utc, total_amount_portfolio FROM tinvest_portfolio_snapshots WHERE account_id = '$account_id' ORDER BY time_utc DESC LIMIT 10 "
    }
   ]
  },
  {
   "title": "Портфель без учета комиссий",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT total_amount_portfolio FROM tinvest_portfolio_snapshots WHERE account_id = '$account_id' ORDER BY time_utc DESC LIMIT 1\r\n"
    },
    {
     "rawSql": "SELECT SUM(payment) FROM tinvest_operations WHERE (account_id = '$account_id' AND operation_type = 19)"
    },
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Позиция SBER",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT quantity \r\nFROM tinvest_portfolio_positions as pos\r\nJOIN tinvest_portfolio_snapshots as snp on pos.portfolio_snapshot_id = snp.id\r\nWHERE snp.account_id = '$account_id'\r\nAND pos.instrument_uid = 'e6123145-9665-43e0-8413-cd61b8aa9b13'\r\nORDER BY snp.time_utc DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "SBER свечи (10 мин)",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time_utc, open, high, low, close, volume FROM tinvest_candles WHERE \"interval\" = 8 ORDER BY time_utc DESC"
    }
   ]
  },
  {
   "title": "Доходность портфеля",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT expected_yield FROM tinvest_portfolio_snapshots WHERE account_id = '$account_id' ORDER BY time_utc DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "История доходности",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT time_utc, expected_yield FROM tinvest_portfolio_snapshots WHERE account_id = '$account_id' ORDER BY time_utc DESC LIMIT 500 "
    }
   ]
  },
  {
   "title": "Торговые сигналы - SB3 DQN",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT time_utc, action FROM trading_signals WHERE predictor_type = 1 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Комиссии за все время",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(payment) FROM tinvest_operations WHERE (account_id = '$account_id' AND operation_type = 19)"
    }
   ]
  },
  {
   "title": "Комиссии брокера и биржи",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT date, payment FROM tinvest_operations WHERE (operation_type = 19 AND account_id = '$account_id') ORDER BY date DESC "
    }
   ]
  },
  {
   "title": "Торговые сигналы - Trend Following",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT time_utc, action FROM trading_signals WHERE predictor_type = 3 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Сделки",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT date, quantity, price, type FROM tinvest_operations WHERE (account_id = '$account_id' AND operation_type <> 19) ORDER BY date DESC "
    }
   ]
  },
  {
   "title": "Торговые сигналы - Random Walk",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT time_utc, action FROM trading_signals WHERE predictor_type = 2 LIMIT 50 "
    }
   ]
  }
 ]
}